In [58]:
import numpy as np

In [59]:
A = np.random.randn(2,3)
B = np.random.rand(3,2,2)
print(A)
print(B)

[[ 1.34608416  0.1538049  -0.21835065]
 [-1.93980392 -1.31842616 -0.09272978]]
[[[0.76774287 0.2681462 ]
  [0.28411139 0.14060502]]

 [[0.40629403 0.3703968 ]
  [0.44373518 0.74521981]]

 [[0.71493287 0.51255382]
  [0.38651943 0.26748016]]]


In [60]:
# la primera columna de A son las entradas así que arranco computando de la segunda columna en adelante
# primer activación de la capa 2 (1 si arranco a contar en 0, de ahora en más empiezo a contar en 0)
print(B[0][0] @ A[:,0])
# segunda activaciónd la capa 1 (desde 0 xd)
print(B[0][1] @ A[:,0])
# primer activación de la capa 2
print(B[1][0] @ A[:,1]) 
# segunda activación de la capa 2
print(B[1][1] @ A[:,1]) 

0.5132954752774531
0.10969167782059874
-0.4258508195544578
-0.9142686491944482


In [61]:
# qué pasa si multiplico más "generalmente"?
print(B[0] @ A[:,0])
print(B[1] @ A[:,1])
# estas serían las columnas de A izquierda a derecha -> arriba a abajo element-wise y arriba abajo -> izquierda a derecha column-wise

[0.51329548 0.10969168]
[-0.42585082 -0.91426865]


In [ ]:
print(B[0:2] @ A[:,0:2])
# esto me está multiplicando de más...

[[[ 0.51329548 -0.23544834]
  [ 0.10969168 -0.14167961]]

 [[-0.17159121 -0.42585082]
  [-0.84827541 -0.91426865]]]


In [ ]:
L=3
N=2

for l in range(L):
    for n in range(N):
        A[l][n] = np.mathmul(M[l][n],A[:,l-1])